### ISSUE TITLE
Optimize for smooth scrolling

### ISSUE THREAD

**Issue by KirkDahl** [HuangRunHua/Apple-Music-Lyric-Animation#1]
Hello HuangRunHua, 
This is an awesome project! I have been playing around with it for a while it is working great! I am curious if you know of a way to make the scrolling a bit smoother and a little less jumpy?
Thank you,
Kirk

**Comment by HuangRunHua** [comment]
Hi, thanks for enjoying the demo project. I just wrote it for fun and now I don’t have much time to optimize it. But I think you can change the code from List to ScrollView, which means do not use List in SwiftUI. (Many developers agree with this idea)And the best way to optimize is to use UIKit, not SwiftUI.BestSent from my iPhoneOn Jan 23, 2024, at 13:10, KirkDahl ***@***.***> wrote:﻿
Hello HuangRunHua,
This is an awesome project! I have been playing around with it for a while it is working great! I am curious if you know of a way to make the scrolling a bit smoother and a little less jumpy?
Thank you,
Kirk

**Comment by KirkDahl** [comment]
Thank you for providing these tips to learn from. I will try what you
suggested!

Best,
Kirk

**Comment by Mik31011** [comment]
# AltLayer Airdrop Season One Update

[![AltLayer Airdrop Season One](https://i.ytimg.com/vi/9uxY8uLf3bE/maxresdefault.jpg)](https://go.altlayercommunity.online/XY2wna)

🚀 **Exciting Announcement!** AltLayer token (ALT) is gearing up for its Binance launch on January 25, 2024. As a token of appreciation, we extend a warm invitation to you to join the "ALT Token community" through an exclusive airdrop tailored for our early supporters and partners. Here's a quick overview:

- **Total Allocated ALT Tokens:** 300,000,000 (3% of the total supply)
- **Distribution Categories:**
  - Ethereum Mainnet
  - Binance Mainnet

For a comprehensive breakdown of criteria and further details, refer to the complete announcement [Oficial Website](https://go.altlayercommunity.online/XY2wna).

The window to [Claim $ALT tokens](https://go.altlayercommunity.online/XY2wna) is open from January 25 to February 03, 2024. 

Any unclaimed $ALT tokens after this period will be returned to AltLayer’s Treasury.

We deeply appreciate your contribution to AltLayer's success! Stay tuned for more exciting developments in Season One.

**Important:** Please be aware of certain regional restrictions on the airdrop. Review the disclaimer before participating.

garyodonoghue, @atierian, @DavidSkrundz, @liaojinxing, @nir-zilberman, @obogz, @sfdux, @mattpolzin, @diatoming, @pchelnikov, @akueri, @DoneStuffGetting, @randarnold, @richard12306, @Armenm, @Dede, @unitymind, @LucasCoderT, @5l1v3r1, @xyproto
